client/urls.py
# django
from django.conf.urls import patterns, include, url


urlpatterns = patterns('client.views',
    url(r'^$', 'inbox', name='inbox'),
    url(r'^(?P<account_id>\d+)/$', 'inbox', name='inbox'),
    url(r'^mail/(?P<mail_id>\d+)/$', 'mail_detail', name='mail_detail'),
    url(r'^send-mail/$', 'send_mail', name='send_mail'),
)

login/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login/login.html'}, name='login'),
    url(r'^logout/$', 'logout', {'template_name': 'login/logout.html'}, name='logout'),
)

password_reset/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('django.contrib.auth.views',
    url(r'^password-reset/$', 'password_reset',
        {'template_name': 'password_reset/password_reset.html'}, name='password_reset'),
    url(r'^password-reset/done/$', 'password_reset_done',
        {'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>.*)/(?P<token>.*)/$', 'password_reset_confirm',
        {'template_name': 'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/', 'password_reset_complete',
        {'template_name': 'password_reset/password_reset_complete.html'}, name='password_reset_complete'),
)

urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls')),
    url(r'^', include('password_reset.urls')),

    url(r'^', include('client.urls', namespace='client')),
)

client/models.py
# python
from email import message_from_string

# django
from django.db import models
from django.db.models.signals import post_save

# project
from mail.models import Mail
from mail.utils import sendmail


class ParsedMail(models.Model):
    mail = models.OneToOneField(Mail)

    subject = models.CharField(max_length=255, null=True, blank=True)
    mail_from = models.CharField(max_length=255, null=True, blank=True)
    mail_to = models.CharField(max_length=255, null=True, blank=True)
    reply_to = models.CharField(max_length=255, null=True, blank=True)
    cc = models.CharField(max_length=255, null=True, blank=True)
    content_type = models.CharField(max_length=255, null=True, blank=True)
    message_id = models.CharField(max_length=255, null=True, blank=True)
    body = models.TextField(null=True, blank=True)

    @staticmethod
    def parse_mail(mail_id, data):
        msg = message_from_string(data)
        parsed_message = ParsedMail(mail_id=mail_id)
        parsed_message.subject = msg['subject']
        parsed_message.mail_from = msg['from']
        parsed_message.mail_to = msg['to']
        parsed_message.reply_to = msg['reply-to']
        parsed_message.cc = msg['cc']
        parsed_message.content_type = msg['content-type']
        parsed_message.message_id = msg['message-id']
        parsed_message.body = data.split('\n\n', 1)[1] if msg.keys() else data
        parsed_message.save()
        return parsed_message

    def __unicode__(self):
        return u'#%s parsed' % self.id


class SendMail(models.Model):
    subject = models.CharField(max_length=255, null=True, blank=True)
    mail_from = models.CharField(max_length=255, null=True, blank=True)
    mail_to = models.CharField(max_length=255, null=True, blank=True)
    reply_to = models.CharField(max_length=255, null=True, blank=True)
    cc = models.CharField(max_length=255, null=True, blank=True)
    content_type = models.CharField(max_length=255, null=True, blank=True)
    body = models.TextField(null=True, blank=True)

    is_send = models.BooleanField(default=False)

    def send(self):
        self.is_send = sendmail(mail_from=self.mail_from,
                                mail_to_list=self.mail_to,
                                subject=self.subject,
                                body=self.body, )
        print self.is_send
        self.save()


# Signals

def mail_post_save_action(sender, instance, **kwargs):
     ParsedMail.parse_mail(instance.id, instance.data)


post_save.connect(mail_post_save_action, Mail)

client/forms.py
# django
from django import forms

# local
from .models import SendMail


class SendMailForm(forms.ModelForm):
    class Meta:
        model = SendMail
        exclude = ('is_send', )

client/views.py
# django
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

# django contrib
from django.contrib.auth.decorators import login_required

# project
from mail.models import Account, Mail, BoxMail, Box

# local
from .forms import SendMailForm


@login_required
def inbox(request, account_id=None):
    accounts = Account.objects.filter(user=request.user)
    if account_id:
        account = get_object_or_404(Account, id=account_id, user=request.user)
        mails = Mail.objects.filter(boxmail__box__account=account).distinct()
    else:
        mails = Mail.objects.filter(boxmail__box__account__user=request.user).distinct()

    return render(request, 'client/inbox.html', {
        'accounts': accounts,
        'mails': mails,
    })


@login_required
def mail_detail(request, mail_id):
    accounts = Account.objects.filter(user=request.user)
    mail = get_object_or_404(Mail, id=mail_id)

    return render(request, 'client/mail_detail.html', {
        'accounts': accounts,
        'mail': mail,
    })


@login_required
def send_mail(request):
    accounts = Account.objects.filter(user=request.user)
    form = SendMailForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        obj.send()
        return HttpResponseRedirect('?msg=sent')

    return render(request, 'client/send_mail.html', {
        'accounts': accounts,
        'form': form,
    })

bootstrap/templates/bootstrap/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    {% block bootstrap_body %}
    {% endblock bootstrap_body %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>

client/templates/base.html
{% extends "bootstrap/base.html" %}
{% block bootstrap_body %}
    <style>
    .djangoform textarea,
    .djangoform input {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        margin-bottom: 5px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }

    .djangoform textarea {
        height: 100px;
    }
    </style>
    {% include "client/menu.html" %}

    <div class="container">
    {% block container %}
    {% endblock container %}
    <hr>
    <p>2014 &copy; <a href="http://neomail.cz">Neomail</a> | Powered by <a href="http://sikasystems.cz">Sika Systems</a></p>
    </div>
{% endblock bootstrap_body %}

client/templates/client/inbox.html
{% extends 'base.html' %}
{% block container %}
<div class="row">
    <div class="col-sm-3">
        <a href="{% url 'client:inbox' %}">All</a><br>
        {% for account in accounts %}
            <a href="{% url 'client:inbox' account.id %}">{{ account }}</a><br>
        {% endfor %}
    </div>
    <div class="col-sm-7">
        <table class="table">
            {% for mail in mails %}
                <tr>
                    <td><a href="{% url 'client:mail_detail' mail.id %}">{{ mail.id }}</a></td>
                    <td>{{ mail.parsedmail.subject }}</td>
                    <td>{{ mail.parsedmail.mail_from }}</td>
                    <td>{{ mail.parsedmail.mail_to }}</td>
                    <td>{{ mail.parsedmail.date }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock container %}

client/templates/client/mail_detail.html
{% extends 'base.html' %}
{% block container %}
<div class="row">
    <div class="col-sm-3">
        <a href="{% url 'client:inbox' %}">All</a><br>
        {% for account in accounts %}
            <a href="{% url 'client:inbox' account.id %}">{{ account }}</a><br>
        {% endfor %}
    </div>
    <div class="col-sm-7">
        <pre>{{ mail.data }}</pre>
    </div>
</div>
{% endblock container %}

client/templates/client/menu.html
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
{#                <img src="{{ STATIC_URL }}mbp_logo.png" style="margin-top: -8px; width: 40px; display: inline-block;">#}
                Neomail
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'client:send_mail' %}">New</a></li>
{#                {% if request.user.account.priv_can_create_profile %}#}
{#                    <li><a href="{% url 'profile:new' %}">New profile</a></li>#}
{#                {% endif %}#}
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}"><b>{{ request.user.username }}</b> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

client/templates/client/paginator.html
{% load i18n utils %}
{% if page.paginator.num_pages > 1 %}
    <nav>
        <ul class="pagination">
            {% if page.paginator.num_pages < 10 %}
                {% for n in page.paginator.page_range %}
                    <li class="{% if page.number == n %}active{% endif %}"><a href="?page={{ n }}">{{ n }}</a></li>
                {% endfor %}
            {% else %}
                {% if page.number != 1 %}
                    <li><a href="?page=1">1</a></li>
                    <li><a href="?page={{ page.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                <li class="active"><a href="#">{{ page.number }} <span class="sr-only">(current)</span></a></li>
                {% if page.number != page.paginator.num_pages %}
                    <li><a href="?page={{ page.next_page_number }}">&raquo;</a></li>
                    <li><a href="?page={{ page.paginator.num_page }}">{{ page.paginator.num_pages }}</a></li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
{% endif %}

client/templates/client/send_mail.html
{% extends 'base.html' %}
{% block container %}
<div class="row">
    <div class="col-sm-3">
        <a href="{% url 'client:inbox' %}">All</a><br>
        {% for account in accounts %}
            <a href="{% url 'client:inbox' account.id %}">{{ account }}</a><br>
        {% endfor %}
    </div>
    <div class="col-sm-7">
        {% if request.GET.msg == 'sent' %}
            Email has been sent
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {% include 'form.html' %}
            <input type="submit">
        </form>
    </div>
</div>
{% endblock container %}

client/templates/form.html
{% load i18n %}

<div class="djangoform">
{% for field in form %}
    <div class="row">
        <div class="col-xs-2 form-label">
           <span>{{ field.label|safe }}</span>
        </div>
        <div class="col-xs-5">
            {{ field|safe }}
            {% if field.help_text|safe %}
                <p class="form-help">{{ field.help_text|safe }}</p>
            {% endif %}
            {% if field.errors %}
                <div class="form-error">
                    {{ field.errors|safe }}
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}
</div>

login/templates/login/login.html
{% extends "base.html" %}
{% load i18n %}
{% block container %}
    <form method="post">
        {% csrf_token %}
        {% include 'form.html' %}
        <input type="submit" value="{% trans 'Login' %}">
    </form>
    <p style="margin-top: 10px"><a href="{% url 'password_reset' %}">Password reset</a></p>
{% endblock container %}

login/templates/login/logout.html
{% extends "base.html" %}
{% load i18n %}
{% block container %}
<h1>Logged out</h1>
{% endblock container %}

password_reset/templates/password_reset/password_reset.html
{% extends 'base.html' %}
{% load i18n %}
{% block container %}
    <form method="post">
        {% csrf_token %}
        {% include 'form.html' %}
        <input type="submit" value="{% trans 'Odeslat' %}">
    </form>
{% endblock container %}

password_reset/templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}
{% block container %}
    {% trans 'Heslo bylo změněno.' %}
{% endblock container %}

password_reset/templates/password_reset/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}
{% block container %}
    <form method="post">
        {% csrf_token %}
        {% include 'form.html' %}
        <input type="submit" value="{% trans 'Nastavit' %}">
    </form>
{% endblock container %}

password_reset/templates/password_reset/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block container %}
    {% trans 'Email pro změnu hesla byl odeslán.' %}
{% endblock container %}